# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc68a853ba21fe61046e418b54c5868460eae47d2cd6808339c7846b8631b4b0513bc1bce28b4c2f818ee3501c1e499dbab9f79524cfdbb3abda80ca94c98838

test:
  secret_key_base: 9d65570e08d80018ef0391e1e8d4f2bde8b57e28ef3061f4981ebb7aa149b9da38ffcd8d7cda64e4af4013ce3a815b406654fd62282115d51554894510fd01eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
